import 'dart:async';
import 'dart:io';
import 'dart:typed_data';

import 'package:sqflite/sqflite.dart';
import 'package:flutter/services.dart';
import 'package:path_provider/path_provider.dart';
import 'med_data.dart';

class DatabaseHelper {
  static final DatabaseHelper _instance = new DatabaseHelper.internal();
  factory DatabaseHelper() => _instance;
  static Database _db;

  Future<Database> get db async {
    if (_db != null) return _db;
    _db = await initDb();
    return _db;
  }

  DatabaseHelper.internal();

  Future<Database> initDb() async {
    Directory dbDir = await getApplicationDocumentsDirectory();
    print('got db path');
    var dbPath = dbDir.path + "MediApp.db";

    // Delete any existing database:
    //await deleteDatabase(dbPath);

    // Create the writable database file from the bundled demo database file:
    ByteData data = await rootBundle.load("assets/MediApp.db");
    List<int> bytes =
        data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    await File(dbPath).writeAsBytes(bytes);
    //var theDb = await openDatabase(dbPath, version: 1, onCreate: _onCreate);
    var theDb = await openDatabase(dbPath);
    return theDb;
  }

  Future<List<MedData>> getdata([String query = ""]) async {
    await Future.delayed(const Duration(seconds: 2));
    var dbClient = await db;
    List<Map> list =
        await dbClient.rawQuery("SELECT * FROM med_data order by name asc");
    List<MedData> md = new List();
    list.forEach((item) {
      md.add(MedData(
          item['name'],
          item['link'],
          item['addr'],
          item['phone'],
          item['pincode'],
          item['map'],
          item['services'],
          item['consultants'],
          item['website'],
          item['img']));
    });
    return md;
  }

  List getservices() {
    return [
      '  Behaviour & Thought Problems  ',
      '  Gastroenteritis Treatment',
      '  Psychological Problems ',
      ' 24 hours Casualty & Emergency Ambulance Services',
      ' 24 hours Pharmacy & Laboratry Services / X-ray',
      ' Alcohol De-addiction Treatment%  Dandruff Treatment ',
      ' Artificial Kidney Dialysis unit',
      ' Automatic Biochemistry Analyzers',
      ' Computers & Accessories',
      ' Contraception Advice  Cosmetic Treatment',
      ' D.G.Sets 125 KVA ',
      ' De-Addiction',
      ' Delivery',
      ' Echo Cardiography & Stress Test',
      ' Endoscopic Ultrasound',
      ' Endoscopist Doctors',
      ' Erectile Dysfunction Treatment ',
      ' Fever',
      ' Fever Treatment',
      ' Foot infection',
      ' Fully S.S.Vertical Autoclaves ',
      ' General Wards, Single& Deluxe Rooms and Super Deluxe Rooms',
      ' Head-Neck-Face injuries',
      ' Horizontal H.P. Sterlizer ',
      ' Hypertension Treatment',
      ' ICU- 8 beds, cardiac& multi-pra moniitors and ventilator',
      ' Neonatal Equipments',
      ' Obesity Treatment',
      ' Pacing, Syringe Pump',
      ' Philips, L&T Patients Monitoring Systems and Crash Carts',
      ' Piles Surgery ',
      ' Pulmonary Function Testing',
      ' Well equipped Physiotherapy unit',
      ' stent Removal',
      '2.2 mm Phaco Surgery for Cataract',
      '24 Hours Services',
      '24 Hrs. Pharmacy',
      '24 hrs pathology',
      '2D ECHO',
      '2D-Echo & CD',
      '3 dedicatedoperation theatres with laminar flow ventilation technology',
      '35 Bedded Hospital',
      '3D Liposuction',
      'A Specialised Dialysis Unit',
      'ACUPUNCTURE',
      'ACUPUNCTURE CLINIC',
      'ALLERGY TEST ',
      'ART Consultant',
      'ASD and VSD surgeries',
      'ATM',
      'AUDIOLOGY & SPEECH THERAPY',
      'AYURVEDIC MEDICINE',
      'Abdominal Pain Treatment',
      'Abnormal, Unusual, Strange Behavior',
      'Abortion',
      'Abortion / Medical Termination of Pregnancy (MTP)',
      'Abortion/ Medical Termination of Pregnancy (MTP)',
      'Accident & Trauma Care',
      'Accident & emergency',
      'Accident and Trauma',
      'Accommodation',
      'Accupressure',
      'Achilles Tendon Rupture Treatment',
      'Acne / Pimples Treatment',
      'Acne And Scars',
      'Acne Treatment',
      'Acne treatment',
      'Acne/ Pimple Scars Treatment',
      'Acne/Scar Treatment',
      'Acrylic Partial Denture',
      'Acupuncture',
      'Acute (sudden onset) renal diseases',
      'Acute Kidney Disease ( AKI ) Treatment',
      'Acute Pancreatitis Treatment',
      'Addiction Medicine',
      'Addictions',
      'Adiana System',
      'Adolescent Medicine',
      'Adolescent Problems',
      'Adolescents Gynecological problems',
      'Adrenal Masses',
      'Adult Nephrology',
      'Advance Dental Implant',
      'Advance Diagnostics Techniques',
      'Advanced Contact Lens Clinic',
      'Advanced Endoscopic Procedures such as EMR, ESD, STER and POEM',
      'Advanced FUE Hair Transplant',
      'Advanced Hernia Surgery Center',
      'Advanced Laparoscopic & hysteroscopic surgery',
      'Aesthetic & Cosmetic Surgery',
      'Aesthetic Dermatology',
      'Aesthetic dermatology',
      'Age Related Macular Degenration',
      'Age-Related Macular Degeneration Treatmen',
      'Ageing Skin',
      'Airway surgery',
      'Alcohol De-addiction Treatment',
      'All Fractures & Trauma',
      'All Vaccinations',
      'All types of advance laparoscopies',
      'All types of minimal invasive/ stitch less general surgeries',
      'Allergy Immunology',
      'Allergy Shots',
      'Allergy Testing',
      'Allergy Treatment',
      'Alopecia',
      'Alopecia Areta Treatment',
      "Alzheimer's Disease",
      'Ambulance',
      'Ambulance Services',
      'Ambulatory BP Monitoring',
      'Anaesthesiology',
      'Anal Fissure Surgery',
      'Anal Fissure Treatment (Non-Surgical)',
      'Androgenetic Alopecia treatment',
      'Anesthesia',
      'Anesthesia & Pain Clinic',
      'Anesthesiology',
      'Anger Control',
      'Anger Management',
      'Anger Management , Sexology , Addiction',
      'Anger Management / Sexology / Mindfulness',
      'Anger Problems',
      'Angiography',
      'Angiography & Angioplasty',
      'Angiology',
      'Angioplasty and Stenting',
      'Ankle-Brachial Index',
      'Ankylosing spondylitis',
      'Ankylosing spondylitis management',
      'Antenatal(pregnancy) check up',
      'Anterior Segment Surgery',
      'Anti Ageing',
      'Anti Aging Treatment',
      'Anti-ageing Treatments',
      'Anti-aging services',
      'Antiageing',
      'Antiaging Treatment',
      'Antisocial Behaviour',
      'Antiwrinkl',
      'Anxiety',
      'Anxiety Disorders Treatment',
      'Aortic Anuerysm Surgery / Endovascular Repair',
      'Appendicitis Treatment',
      'Arm Reduction',
      'Arterial Bypass Surgery',
      'Arthoscopy',
      'Arthritis',
      'Arthritis Care',
      'Arthritis Management',
      'Arthroplasty',
      'Arthroscopic ACL, PCLreconstruction, and Meniscal repair surgeries',
      'Arthroscopic Surgeries for Instability of shoulder and cuff repaair',
      'Arthroscopic rotator cuff repair',
      'Arthroscopic shoulder stabilization',
      'Arthroscopicmeniscus repair/excision',
      'Arthroscopy',
      'Arthroscopy & Sports Medicine',
      'Artificial Insemination',
      'Artificial Kidney Dialysis',
      'Artificial Teeth',
      'Assessment of behavioral problemsand development delays',
      'Assisted Embryo Hatching',
      'Asthma',
      'Asthma and allergies detection in children',
      'Astigmatism',
      'Audiology',
      'Audiology & Speech Therapy',
      'Audiology & speech therapy',
      'Audiometry',
      'Audiometry and Speech Therapy%Blood Collection Center%Blood Storage Center%Cath Lab%Colour Doppler Study%CT Scan Centre%Digital X-Ray%Dialysis Unit%Electrocardiogram (E.C.G)%EEG/EMG%Eye Donation Center%Echocardiogram / 2D-Echo%Intensive Cardiac Care Unit (ICCU)%Mammography%Operation Theater',
      'Auto augmentation of Breast',
      'Avastin Injections',
      'Ayurvedic Consultation',
      'Azoospermia Treatment',
      'B-K Diagnostic Ultrasound',
      'BEFIT weight reduction clinic',
      'BPS Dentures Fixing',
      'BRCA Gene Test',
      'Back Pain Physiotherapy',
      'Back pain',
      'Baldness Treatment',
      'Balloon angioplasty (PTCA) with stenting',
      'Bankart Repair',
      'Bariatric & Metabolic Surgery',
      'Bariatric Surgery',
      'Bartter syndrome',
      'Basic Eye Check-up',
      'Beauty Care',
      'Beauty Facial',
      'Behavioral Medicine',
      'Behaviour & Thought Problems',
      'Belly Casting',
      'Bilirubin Test',
      'Biofibre Hair Implant',
      'Biologic therapy for arthritis',
      'Bipolar Disorder Treatment',
      'Birth Services',
      'Birthing',
      'Bladder Cancer SurgeryLaser Fistula Treatment',
      'Blade-free Cataract Surgery',
      'Blastocyst',
      'Blastocystculture',
      'Bleeding Gums Treatment',
      'Bleeding Gums and Gum Disease',
      'Blood Bank',
      'Blood Gas Analyzer, Fully Automatic Cell Counter',
      'Blood Grouping',
      'Blood Pressure Test',
      'Blood Storage Center',
      'Blood Test',
      'Blood in Semen',
      'Blood in Urine (Hematuria) Treatment',
      'Blood in urine (hematuria) management',
      'BloodTest',
      'Body Contouring',
      'Body Contouring & Skin Tightening',
      'Body Treatments',
      'Body sculpture & recontouring',
      'Bone Augmentation & Sinus Lift',
      'Bone Density Test/Densitometry',
      'Bone Marrow Transplant - BMT',
      'Bone Marrow Transplantation',
      'Bone Scan',
      'Bone Trauma',
      'Bone and Joints',
      'Botox',
      'Botox Injections',
      'Botox and Filler Injection',
      'Brachial Plexus &nerves injuries',
      'Brain & Spine Care',
      'Brain Tumors',
      'Breast Augmentation',
      'Breast Care',
      'Breast Cosmetic Surgery',
      'Breast Examination',
      'Breast Lift Augmentation',
      'Breast Lift Surgery',
      'Breast Oncology',
      'Breast Reduction',
      'Breast Reduction Surgery',
      'Breast Reshaping',
      'Brow & Forehead Lift',
      'Brow Lift',
      'Burn Surgery',
      'Buttock Implant',
      'C-ARM Facility',
      'C-Reactive Protein Test',
      'CA-125 Test',
      'CABG beating heart surgery',
      'CARDIAC REHABILITATION',
      'CARDIOLOGY',
      'CATARACT CLINIC',
      'CERVICAL CANCER DETECTION ',
      'CHEST MEDICINE',
      'COLOR DOPPLER',
      'CONSULTING ROOMS',
      'COPPER T REMOVAL ',
      'CORNEA CLINIC',
      'COSMETIC SURGERY',
      'CSF Rhinorrhoea Repair Surgery',
      'CT Scan',
      'CT- Scan',
      'CVTS',
      'Caesarean Section',
      'Caesarean Section (C Section)',
      'Cancer',
      'Cancer Care',
      'Cancer Centre',
      'Cancer Management',
      'Cancer Screening',
      'Cancer Screening (Preventive)',
      'Cancer Screening(Cervix/ Breast)',
      'Cancer Surgeons%Cardio vascular and thoraci-suregeon%Chest Physician%Chest Pysiotherapist%Diabetologist%Diabetic foot surgeon%Ddermatologists%Dental surgeon%Dietician%E.N.T%Endocrinologist%General surgeons%Gastroentrologist%Gynaec onco suregeon%General OPD%Infectious diesease%Interventional radiologist%Neuro surgeon%Neuro physician%Orthopaedic joint replacement surgeon%Obstetricians gynecologists%Ophthalmologist%Onco Physicain%Oral maxillofacial suregeon%Physician%Pediatrician%pediatrician-surgeon%Psychiatrists%Plastic surgeons%Physiotherapy%Rheumatologist%Spine surgeon%Urologist%Varicose vein/CT Biopsy%Vitro retina suregeon%Vascular interventional Radiologist/Sonologist',
      'Cancer Surgery',
      'Cancer surgery',
      'Car Parking/Valet Parking',
      'Cardiac Ambulance',
      'Cardiac Car',
      'Cardiac Care',
      'Cardiac Catheterization and interventional services for children',
      'Cardiac Check ups',
      'Cardiac Clinic',
      'Cardiac Stress Test',
      'Cardiac surgeries',
      'Cardiac/Heart Clinic',
      'Cardio / Onco Rehab',
      'Cardio Thoracic and Vascular Surgery',
      'Cardiography',
      'Cardiology',
      'Cardiology & CVTS',
      'Cardiology pulmonary diagnostics',
      'Cardiothoracic & Vascular Surgery',
      'Cardiothoracic Surgery',
      'Cardiovascular',
      'Cardiovascular & Thoracic Surgery',
      'Cardiovascular Disease',
      'Cardiovascular and Pulmonary Physiotherapy',
      'Cashless Facility for TPA/Mediclaim',
      'Cashless Mediclaim Facilities Process work flow',
      'Cashless Services',
      'Cashless mediclaim Health Insurance',
      'Cast Partial Denture',
      'Casualty',
      'Cataract',
      'Cataract Clinic',
      'Cataract Surgery',
      'Cataract Treatment:',
      'Cataract surgery',
      'Cath Lab',
      'Central O2 & N2o Supply',
      'Centres & Excellence',
      'Cerebral Palsy',
      'Cerebral Palsy Clinic',
      'Cervical Cerclage',
      'Cervical spine',
      'Chemical Peel',
      'Chemical Peels',
      'Chemonucleolysis',
      'Chest Medicine',
      'Chest Medicine Centre',
      'Chest Physician',
      'Child Birth',
      'Child Counselling:',
      'Child Development Disease Treatment',
      'Child Growth and Developement',
      'Child Psychologist',
      'Child Vaccination',
      'Child and Adolescent Problems',
      'Children Dentistry (Pediatric Dentistry)',
      'Children’s Eye Disorder',
      'Chin Surgery',
      'Cholesterol Test',
      'Choronic Health Issues Management',
      'Chronic (slow ongoing decline in renal function) renal diseases',
      'Chronic Kidney Disease ( CKD )',
      'Chronic Pain Treatment',
      'Chronic Urticaria',
      'Chronic and recurrent urinary tract infection management',
      'Circumcision',
      'ClayMoulding',
      'Cleft lip / Cleft palate',
      'Clinical Departments',
      'Clinical Pathology',
      'Clinical Specialities',
      'Clinics & KH',
      'Cochlear Implants',
      'Cognitive Behavioral Therapy (CBT)',
      'Cold',
      'Colonoscopy',
      'Color Doppler',
      'Colorectal Clinic',
      'Colorectal Surgery',
      'Colposcopy',
      'Colposcopy Examination',
      'Column traumatology',
      'Common Skin Treatment',
      'Community Health Centre',
      'Community Out Reach Programme',
      'Company & insurance tie-up',
      'Complete Breast Care (CBC)',
      'Complete Evaluation Of Couple',
      'Complete Evaluation of Couples',
      'Complete/Partial Dentures Fixing',
      'Complex ovarian cysts',
      'Complex primary arthroplasty',
      'Complicated hysterectomies procedures',
      'Comprehensive',
      'Comprehensive Diabetic care',
      'Comprehensive Eye Checkup',
      'Comprehensive imaging for children',
      'Computed Corneal Topography',
      'Computer navigated joint replacement surgery',
      'Computerised Stress Test',
      'Concentration Problems',
      'Congenital Disorders Evaluation / Treatment',
      'Congenital Ear Problem Treatment',
      'Congenital Hand Deformities',
      'Congenital anomalies, evaluation and treatment',
      'Congenital nephrogenic diabetes insipidus',
      'Congenitaldiseases',
      'Conscious Sedation',
      'Conservative Dentistry',
      'Consultation',
      'Consultation and treatment of Spine and Related Problems',
      'Consultation for Liver Disease, constipation, chron’s disease, ulcerative colitis, irritable bowel syndrome',
      'Contact Lens Prescription',
      'Contraception Advice',
      'ContraceptionCounseling',
      'Contrast echocardiography',
      'Corn Removal',
      'Cornea',
      'Cornea Clinic',
      'Cornea/Refractive Surgery',
      'Corneal Collagen Cross-Linking',
      'Corneal Transplant',
      'Corneal Transplantation',
      'Corneal Ulcer Treatment',
      'Coronary Angiogram',
      'Coronary Angiography',
      'Coronary Angioplasty / Bypass Surgery',
      'Corporate ,TPA/Insurance',
      'Corporate Dental Camps',
      'Corporate DentalCamps',
      'Corporate Services',
      'Correction of deformities',
      'Cosmetic (Tooth Coloured) Fillings',
      'Cosmetic Dentistry',
      'Cosmetic Gum Treatment',
      'Cosmetic Nose Surgery',
      'Cosmetic Ophthalmology',
      'Cosmetic Surgery',
      'Cosmetic Surgery (Plastic Surgery)',
      'Cosmetic Treatments',
      'Cosmetic Veneers/Bonding',
      'Cosmetic and Plastic Surgeries',
      'Cosmetic plastic surgery ',
      'Cosmetic surgery',
      'Cosmetic/ Aesthetic Dentistry',
      'Cosmeto Gynecology Treatments',
      'Cosmetology Related services',
      'Cosmetology and Plastic Surgery',
      'Counselling',
      'Craniotomy',
      'Critical Care',
      'Critical Care Unit',
      'Crossed Eye Management',
      'Crowns and Bridges Fixing',
      'Cryopreservation',
      'Custom made Replacement Arthroplasty',
      'Customised Spectacles',
      'Customising orthoses',
      'Cyclical Medicine',
      'Cystectomy',
      'Cystoscopy',
      'D&C (Dilation and Curettage)',
      'D&C (Dilation andCurettage)',
      'DELUXE & SEMI-DELUXE ROOMS',
      'DENTAL IMPLANT',
      'DENTAL SPECIALITY CLINIC',
      'DENTISTRY',
      'DERMATOLOGY',
      'DHI Hair Transplant',
      'DIABETOLOGY',
      'DIALYSIS',
      'DIETETICS & NUTRITION',
      'DIETICIAN',
      'DIETITIAN',
      'Dandruff',
      'Dandruff Control',
      'Day Care',
      'Day Care and Home Care',
      'Day and night Pharmacy',
      'Daycare',
      'De-Addiction',
      'DeAddiction Counselling',
      'Deafness Treatment',
      'Deafness – both from birth and acquired later',
      'Decompression and stabilization for  Tuberculosis of spine',
      'Delivery Suites',
      'Delivery –Painless Delivery',
      'Dengue Fever Treatment',
      'Dental',
      'Dental Braces Fixing',
      'Dental Care',
      'Dental Ceramics',
      'Dental Crowns (Caps) & Bridges',
      'Dental Fillings',
      'Dental Implant Fixing',
      'Dental Implant Restorations & Implant Over Dentures',
      'Dental Implants',
      'Dental OPD',
      'Dental Sealant',
      'Dental Services',
      'Dental Surgery',
      'Dentistry',
      'Department Scorecard',
      'Department of Bone and Joint care (Orthopaedics)',
      'Department of Child Health',
      'Department of Dermatology and cosmetology',
      'Department of Ear Nose and Throat diseases',
      'Department of Medicine',
      'Department of Physiotherapy and Occupational therapy',
      'Department of Surgery & Urology',
      'Departments',
      'Depression',
      'Depression Treatment',
      'Dept. of Medicine',
      'Dermabrasion',
      'Dermabrasion ',
      'Dermaroller',
      'Dermaroller/Stem Cells',
      'Dermatology',
      'Dermatology Clinic',
      'Dermatopathology',
      'Dermatosurgery',
      'Dermo-Cosmetology Clinic/ Dentistry',
      'Detoxification',
      'Development Assessment',
      'Diabetes',
      'Diabetes Care',
      'Diabetes Clinic ',
      'Diabetes Induced Erectile Dysfunction',
      'Diabetes Management',
      'Diabetes Management ',
      'Diabetic Check up',
      'Diabetic Clinic',
      'Diabetic Retinopathy',
      'Diabetic Retinopathy Screening/ Treatment',
      'Diabetology',
      'Diagnosis',
      'Diagnosis & Evaluation',
      'Diagnostic',
      'Diagnostic & Interventional Endoscopy',
      'Diagnostic & Therapeutic Endoscopy',
      'Diagnostic & Therapeutic Lower Gastrointestinal Endoscopy',
      'Diagnostic & Therapeutic Upper Gastrointestinal Endoscopy',
      'Diagnostic & Therapeutic colonoscopy',
      'Diagnostic - Color Doppler',
      'Diagnostic Center',
      'Diagnostic Centre',
      'Diagnostic Facilities',
      'Diagnostic Laparoscopy',
      'Diagnostic Procedures',
      'Diagnostic Radiology',
      'Diagnostic Services',
      'Diagnostic and monitoring',
      'Diagnostic arthroscopy and biopsy',
      'Diagnostic gastroscopy and colonoscopy',
      'Diagnostics',
      'Diagnostics & Treatment for Glaucoma',
      'Dialysis',
      'Dialysis Chair',
      'Dialysis Unit',
      'Diet Counseling ',
      'Diet For Kids',
      'Diet, Obesity & Weight Loss',
      'Dietary Counseling',
      'Dietary-Services',
      'Dietetics',
      'Dietetics and Clinical Nutrition',
      'Dietitians',
      'Digestive Care',
      'Digital X-Ray',
      'Digital X-rays for Intra and Extra Oral View',
      'Digital retraction',
      'Dimple Creation',
      'Dimple Creation Surgery',
      'Diphtheria',
      'Direct Visual Internal Urethrotomy (DVIU)',
      'Disc replacement',
      'Discectomy',
      'Diseases in Pregnancy',
      'Dissection',
      'Divorce',
      'Doctor Profiles',
      'Doppler Scan In Pregnancy',
      'Double Chin Treatment',
      'Double Chin Treatments',
      'Drug Abuse & DeAddiction Therapy',
      'Dry Eye - Evaluation / Treatment',
      'Dry Eye Treatment',
      'ECG',
      'EEG Department',
      'EEG brain',
      'EMERGENCY/CASUALITY ROOM',
      'EMG brain',
      'ENDOCRINOLOGY',
      'ENDOSCOPY',
      'ENT',
      'ENT COnsultation',
      'ENT Checkup (General)',
      'ENT Clinic',
      'ENT Endoscopy',
      'ENT Surgeries',
      'ENT Surgery',
      'ENT Treatment Unit',
      'ENT treatment',
      'ERCP',
      'EUS',
      'EXTENDED RANGE OF VISION IOL',
      'Ear Ache',
      'Ear Drum Repair',
      'Ear Lobe Correction / Repair',
      'Ear Micro Surgery',
      'Ear Pain',
      'Ear Surgery',
      'Ear Surgery-Otoplasty',
      'Ear Wax (Cerumen) Removal',
      'Ear and Nose Piercing Apparatus',
      'Ear deformities – Microtia / Bat ears etc.',
      'Ear discharge',
      'Ear tumors treament .',
      'Ear, Nose, Throat Treatment',
      'Ear/Nose/ThroatClinic',
      'EarDrum Repair',
      'Eardrum Rupture Treatment',
      'Early Ambulatory Surgery',
      'Early Parenting Issues',
      'Early pregnancy Issues',
      'Echocardiogram',
      'Ectopic pregnancies',
      'Eczema Treatment',
      'Egg Sharing and Donation',
      'Elbow Replacement',
      'Electrocardiogram (ECG)',
      'Electrolyte or acid-base imbalance correction',
      'Electrophysiology',
      'Electroporation',
      'Embryo Donation',
      'Embryo adoption',
      'Emergency & Trauma',
      'Emergency / casualty',
      'Emergency Critical Care',
      'Emergency Department',
      'Emergency Endoscopic Services',
      'Emergency Medicine',
      'Emergency Medicine & Trauma',
      'Emergency Medicine ENT, Head and Neck Surgery',
      'Emergency Response',
      'Emergency Services',
      'Emergency-Services',
      'Emergency/Trauma',
      'Emotional Outbursts',
      'Endo Surgery Or Apicoectomy',
      'Endocrinolocgy/Rheumatology',
      'Endocrinology',
      'Endocrinology (Hormones)',
      'Endocytoscopy [optical biopsy for early cancer detection]',
      'Endometriosis',
      'Endomyocardial biopsy',
      'Endoscopic Balloon Therapy',
      'Endoscopic Obesity Treatment - Intra Gastri Balloon Placement / Endoscopic Gastric Plication [for obesity]',
      'Endoscopic Plastic Surgery',
      'Endoscopic Surgery',
      'Endoscopic excision of intraventricular tumors',
      'Endoscopic ligations',
      'Endoscopic surgery spine',
      'Endoscopies',
      'Endoscopy',
      'Endoscopy, Laprpscopy',
      'Endosurgery',
      'Endovascular',
      'Epilepsy',
      'Evacuation of brain hematomas',
      "Evaluation of mental retardation, Down'S syndrome",
      'Events',
      'Executive Health Checkups',
      'External fixator',
      'Eye / ENT Check-Up',
      'Eye Checkup - General',
      'Eye Spa',
      'Eye Surgery',
      'Eyelid Surgery-Blepharoplasty',
      'FAIRNESS',
      'FESS',
      'FUE Scar Less Method',
      'FUE Stitch Less',
      'Face Lift',
      'Face Surgery',
      'Face lift',
      'Facial',
      'Facial Make Over',
      'Facial Plastic',
      'Facial Rejuvenation',
      'Facial paralysis secondary to ear disease treament',
      'Facials',
      'Facilities',
      'Family General Practice',
      'Family Planning',
      'Family Practice',
      'Family Problems',
      'Fanconi renotubular syndrome',
      'Fat Injection',
      'Female Hair Loss',
      'Female Sexual Problems',
      'Fertility & IVF',
      'Fertility IVF',
      'Fertility Treatment',
      'Fertility enhancing diagnostic',
      'Fertility evaluation and counselling',
      'Fibroids',
      'Fibroids Removal Surgery',
      'Filaria Treatment',
      'Fillers',
      'First Aid',
      'Fitness Training',
      'Fixed Partial Denture (FPD)',
      'Flap Surgery',
      'Flat back',
      'Flexible Partial/Complete Denture',
      'Foetal cardiac services',
      'Foot Assessment',
      'Foot care management',
      'For The Parents',
      'Forehead Lift',
      'Foreign Body in Eyes, Ears, Nose and Throat',
      'Foreign body in Throat, Ear & Nose Removal',
      'Fractional CO2 Laser Skin Resurfacing',
      'Fractional Skin Rejuvenation',
      'Fracture Clinic',
      'Fracture Plaster',
      'Fracture Treatment',
      'FractureTreatment',
      'Freckles Treatment',
      'Freezing of eggs',
      'Freezing of embryos (vitrification)',
      'Freezingof sperms',
      'Frozen shoulder Physiotherapy',
      'Full Denture (Acrylic)',
      'Full Mouth Rehabilitation',
      'Functional Endoscopic Sinus Surgery - FESS',
      'GENERAL MEDICINE',
      'GENERAL SURGERY',
      'GI Cancer Surgery',
      'GLAUCOMA CLINIC',
      'GYNAECOLOGY & OBSTETRICS',
      'GYNECOMASTIA',
      'Gait Lab',
      'Gall Bladder (Biliary) Stone Treatment',
      'Gall Bladder Surgery',
      'Gallbladder Surgery',
      'Gastric Balloon',
      'Gastric Plication',
      'Gastric Surgery',
      'Gastritis Treatment',
      'Gastro Enterology',
      'Gastro Enterology  ',
      'Gastroenteritis Treatment',
      'Gastroenterologists',
      'Gastroenterology',
      'Gastroenterology / Endoscopy',
      'Gastroenterology Dept With Endoscopy',
      'Gastroentologist',
      'Gastrointestinal Disorders',
      'Gastrointestinal Endoscopic Mucosal Resection',
      'Gastroscopy',
      'General',
      'General Dentistry',
      'General Imaging',
      'General Medical ',
      'General Medical Consultation',
      'General Medicine',
      'General Physician',
      'General Practice',
      'General Surgery',
      'General pediatrics',
      'General surgery',
      'Genetic disorders, genetic counseling',
      'Genital Injury',
      'Geriatric Medicine',
      'Geriatric Problems',
      'Gestational Diabetes Management',
      'Giant Aneurysm',
      'Giddiness (vertigo) assessment',
      'Glaucoma',
      'Glaucoma Clinic',
      'Glaucoma Evaluation / Treatment',
      'Glaucoma Treatment',
      'Glycolic Peel',
      'Gonorrhea infection of the newborn',
      'Gout',
      'Govt.Reg. M.T.P. Centre',
      'Grief',
      'Group B streptoccus infection',
      'Growth & Development Evaluation / Management',
      'Growth Scan',
      'Growth and development assessment',
      'Gum Disease',
      'Gum Disease & Periodontics',
      'Gum Disease Treatment/ Surgery',
      'Gummy Smiles',
      'Gynacology',
      'Gynae Problems',
      'Gynaec surgery',
      'Gynaec. Surgeries',
      'GynaecConsultation',
      'Gynaecological Clinic',
      'Gynaecological Endoscopy',
      'Gynaecological Work',
      'Gynaecology',
      'Gynaecology & Minimal Access Surgery',
      'Gynaecology & Obstetrics',
      'Gynecologist',
      'Gynecology',
      'Gynecomastia Treatment',
      'HAIR RESTORATION',
      'HAIR TRANSPLANT',
      'HBA1C Test',
      'HIV & AIDS CARE',
      'HOMEOPATHY',
      'HOMEOPATHY CLINIC',
      'HORMONAL TESTING ',
      'HPB & Liver Surgery',
      'HPV Test',
      'Haemorrhage Treatment',
      'Hair',
      'Hair Care',
      'Hair Care Products for Maintenance',
      'Hair Disease',
      'Hair Extensions',
      'Hair Fall Treatment',
      'Hair Loss Treatmen',
      'Hair Loss Treatment',
      'Hair Regrowth',
      'Hair Related',
      'Hair Transplant',
      'Hair Transplant Surgery',
      'Hair Treatment',
      'Hair Treatments/Hair Spa',
      'Hair disorders',
      'Hair fall and Thinning for women',
      'Hair loss in men',
      'Hairfall / Acne/ Allergies/Weight Loss-Gain/PCOD',
      'Hand Pain',
      'Hand Pain Treatment',
      'Hand Rejuvenation',
      'Hand Surgery',
      'Hand, wrist, elbow shoulder conditions',
      'Harmonal Assement For Female',
      'Head Up Tilt Test (HUTT)',
      'Head and Neck Infection Treatment',
      'Head and Neck Pain',
      'Head and Neck Tumor / Cancer Surgery',
      'Head-Neck-Face tumor and, cancer management',
      'Headache',
      'Headache Management',
      'Health Check',
      'Health Check Up Plans',
      'Health Check up',
      'Health Check-up Plans',
      'Health Checkup',
      'Health Checkup (General)',
      'Health Checkup (Pediatric)',
      'Health Checkup Packages',
      'Health Packages',
      'Health at Home',
      'Healthcare Services',
      'Hearing Aid Fitting',
      'Hearing Aids',
      'Hearing Center',
      'Hearing Deficiency Assessment',
      'Hearing Impairment',
      'Hearing Loss',
      'Hearing Problem',
      'Hearing, Speech Impairment',
      'Heart Care',
      'Heart Centre',
      'Heart Conditions',
      'Heart Scan',
      'Heart Transplantation',
      'Heart Valve Replacement /Repair Surgery',
      'Heart and Lung Transplant',
      'Hematology',
      'Hematology (Blood)',
      'Hemoglobin Test',
      'Hepatologist',
      'Hepatology',
      'Hereditary and metabolic disorders',
      'Hereditary renal disorders',
      'Hernia Center',
      'Hernia Repair Surgery',
      'Herniated Disc',
      'High Risk Pregnancy',
      'High precision modern equipments',
      'High-Risk Pregnancy Care',
      'Hip Replacement',
      'Hip Replacement surgery',
      'Hip Resurfacing',
      'Hip, Ankle, Knee Injury',
      'Holter BP monitoring / Ambulatory Monitoring',
      'Holter monitoring',
      'Home Care',
      'Home Health Service',
      'Homeopathic Consultation',
      'Homeopathy ',
      'Homeopathy.',
      'Hormonal Assessment for Females',
      'Hospital Highlights',
      'Hydra Facial Treatment',
      'Hydrocele Treatment (Surgical)',
      'Hymenoplasty',
      'Hymenoplasty ',
      'Hyper Pigmentation Treatment',
      'Hyperbaric Medicine',
      'Hyperbaric Oxygen Therapy',
      'Hypophysectomy',
      'Hysterectomy (Abdominal/Vaginal)',
      'Hysteroscopy',
      'I.C.U.',
      'IASIS Offers',
      'ICCU',
      'ICICI Bank',
      'ICSI',
      'ICSI (intracytoplasmic sperm injection)',
      'ICU',
      'IMSI',
      'INDOOR SECTION',
      'INTENSIVE CARE UNIT',
      'IPD',
      'IPD with A/C & Deluxe Room',
      'IPL Hair Removal',
      'IUI',
      'IUI (intrauterine insemination)',
      'IUI-Intrauterine-insemination',
      'IVF & ET',
      'Image guided spine surgery',
      'Imaging',
      'Imaging & Radiology',
      'Immediate Dentures',
      'Immunization',
      'Impaction / Impacted Tooth Extraction',
      'Implant services- cheek, chin, breast, calf implants',
      'In Office Bleaching',
      'In Patient Accommodation',
      'In Patient Rooms Facilities',
      'In-Patient Department',
      'In-Patient Services',
      'In-Vitro Fertilization (IVF)',
      'Infant & Child nutrition',
      'Infection in spine',
      'Infections and infectious diseases treatment',
      'Infectious Disease',
      'Infectious Disease Treatment',
      'Infectious Diseases',
      'Infectious Diseases Specialist',
      'InfectiousDisease Treatment',
      'Infertility',
      'Infertility Clinic',
      'Infertility Clinic, and Family Planning Center.',
      'Infertility Evaluation / Treatment',
      'Infertility Service',
      'Infertility Work',
      'Infertility with IUI setup',
      'Inflammatory Bowel Disease (IBD) Treatment',
      'Injectable Fillers',
      'Insanity',
      'Insomnia (Sleeplessness)',
      'Insulin Treatment',
      'Intelligence quotient',
      'Intensive Care',
      'Intensive Care Unit ( ICU )',
      'Intensive Care Unit (ICU)',
      'Intensive Care Units',
      'Internal Medicine',
      'Internal Medicine & Endocrinology',
      'Internal mammary',
      'International Patients',
      'Interventional Cardiology',
      'Interventional Neurology',
      'Interventional Neuroradiology',
      'Interventional Radiology',
      'Interventional neuro-radiology',
      'Intestine Surgery',
      'Intra-Uterine Insemination (IUI)',
      'Intra-aortic balloon pump (IABP) Insertion',
      'Intra-articular (joint) injections',
      'Intracytoplasmic Sperm Injection (ICSI)',
      'Intrauterine Insemination (Iui)',
      'Intravascular ultrasound (IVUS) for Mechanical Thrombectomy System',
      'Invasive Cardiac',
      'Invasive Cardiology',
      'Investigation and Treatment of Epistaxis',
      'Invisible/Clear Braces',
      'Irritable Bowel Syndrome ( IBS ) Treatment',
      'Isolation NICU',
      'Joint Dislocation Treatment',
      'Joint Mobilization',
      'Joint Pain',
      'Joint Pain Management',
      'Joint Pain Physiotherapy',
      'Joint Pain Treatment',
      'Joint Replacement',
      'Joint Replacement Surgeon',
      'Joint Replacement Surgeries',
      'Joint Replacement Surgery',
      'Joint and Muscle Problems',
      'Joint and spine Disorder',
      'Joint replacement center',
      'KERATOCONUS CLINIC',
      'Kaya Bridal',
      'Kaya Hair Health Boost System',
      'Kaya Hair Nutri Infusion Therapy',
      'Kaya Hair Restore Expert Transplant Solutions',
      'Kaya Hairfree Gentle Touch',
      'Kaya Intensive Hair Root Therapy',
      'Kaya Platelet Rich Plasma Therapy',
      'Keyhole Surgery',
      'Kidney Disease Treatment',
      'Kidney Stone Treatment',
      'Kidney Transplant',
      'Kidney Transplantation',
      'Knee Braces For Osteoarthritis',
      'Knee Osteotomy',
      'Knee Pain',
      'Knee Pain Treatment',
      'Knee Replacement',
      'Knee care',
      'Kyphoplasty',
      'Kyphosis',
      'LAPROSCOPY',
      'LASER HAIR REMOVAL',
      'LASER VAGINAL TIGHTENING ',
      'LASIK Eye Surgery',
      'LASIK surgery',
      'LGBT Counselling',
      'LLLT(Low Level Laser Therapy)',
      'Lab Services',
      'Lab Tests',
      'Labiaplasty',
      'Labiaplasty ',
      'Laboratory',
      'Laboratory /xBlood Bank',
      'Laboratory Medicine',
      'Laboratory Services',
      'Labour Room',
      'Labour Room with 2 beds',
      'Lactation Consultation',
      'Lactation Counselling',
      'Lactic Peel',
      'Laminates',
      'Laminectomy',
      'Laparoscopic & Minimal Access Surgery',
      'Laparoscopic Adhesion Removal',
      'Laparoscopic Adjustable Gastric Band',
      'Laparoscopic Appendicectomy',
      'Laparoscopic Cholecystectomy',
      'Laparoscopic Hernial Repair',
      'Laparoscopic Hiatus Hernia Repair',
      'Laparoscopic Management of Ectopic Pregnancy',
      'Laparoscopic Salpingo-oophorectomy',
      'Laparoscopic Sleeve Resection',
      'Laparoscopic Surgery',
      'Laparoscopic Surgery (Obs & Gyn)',
      'Laparoscopic Tubal Recanalization',
      'Laparoscopic appendisectomy, cholecystectomy',
      'Laparoscopicmanagement of Myoma',
      'Laparoscopy',
      'Laproscopic Tubal Recanalization Surgery',
      'Laproscopic appendicectomy',
      'Laproscopy and Endoscopy (Minimum access surgeries)',
      'Laryngoscopy',
      'Laryngotracheal injuries correction',
      'Laser',
      'Laser Acne Reduction',
      'Laser Dentistry',
      'Laser Fissure Surgery',
      'Laser Gum Surgery',
      'Laser Hair Reduction',
      'Laser Hair Removal',
      'Laser Hair Removal - Face',
      'Laser Hair Removal Treatment',
      'Laser Photocoagulation',
      'Laser Piles Treatment',
      'Laser Procedures for Retinal Diseases',
      'Laser Prostatectomy',
      'Laser Refractive & Cataract Surgery',
      'Laser Removal of Tattoos',
      'Laser Resurfacing',
      'Laser Services',
      'Laser Skin Rejuvenation',
      'Laser Skin lightening',
      'Laser Surgeries for Head and Neck Lesions',
      'Laser Therapy',
      'Laser Treatment',
      'Laser Vaginal Rejuvenation',
      'Laser VaginalTightening',
      'Laser liposuction',
      'Laser skin resurfacing',
      'Laser spine surgery',
      'LaserAssisted hatching',
      'LaserRemoval of Tattoos',
      'Lasers therapies',
      'Lasik',
      'Lasik Surgery',
      'Lasik for Glasses Removal',
      'Latest Technique for Skin Technique',
      'Lazy Eye Treatment',
      'Leucoderma Treatment',
      'Ligament Reconstruction',
      'Ligament reconstruction',
      'Limb Deformities',
      'Line and Wrinkle Smoothing',
      'Lip Surgery',
      'Lipid Profile',
      'Liposuction',
      'Liposuction & Sculpting',
      'Listhesis',
      'Lithotripsy',
      'Liver Disease Treatment',
      'Liver Services',
      'Liver Surgery',
      'Liver Transplant',
      'Liver Transplantation',
      'Liver resection',
      'Loneliness',
      'Lordosis',
      'Loss of Interest',
      'Low Confidence',
      'Low Level Laser Therapy',
      'Low Self esteem',
      'Low Sperm Count Treatment',
      'Low Vision Aid Clinic',
      'Low vision',
      'Lower Back Pain',
      'Lower Back Pain, Neck Pain',
      'Lumbar Spine',
      'Lung Care Centre',
      'Lung Function Test',
      'Lung Transplantation',
      'Lung surgeries like lobectomy, pneumonectomy etc.',
      'MANICURE/ PEDICURE',
      'MATERNITY AND INFERTILITY CLINIC',
      'MDS (Oral Surgery)',
      'MEDICAL STORE',
      'MRI machine',
      'MTP',
      'MTP services',
      'Magnetic Resonance Imaging ( MRI)',
      'Male Breast Reduction',
      'Male Hair Loss',
      'Male Sexual Problems',
      'Marital Problems',
      'Marriage Counselling',
      'Marriage/ Marital Counselling',
      'Maternal Care/ Checkup',
      'Maternal care',
      'MaternalCare/ Checkup',
      'Maternity Care',
      'Maternity Department',
      'Maternity Home',
      'Max Pharmacy',
      'Maxillo Facial Surgery',
      'McKinzie Treatment for Spine',
      'Measles',
      'Measles Treatment',
      'Meconium aspiration syndrome',
      'Mediastinal tumour excision',
      'Medical Emergency',
      'Medical Gastroenterology & Endoscopy',
      'Medical Oncology',
      'Medical Oncology Clinic - Multi disciplinary Team Consultation in G.I. Oncology [for cancers of food pipe / stomach / small intestine / large intestine / liver / gall bladder / bile ducts / pancreas]',
      'Mega Liposuction',
      'Melasma Treatment',
      'Memory Improvement',
      'Menstrual dysfunction treatment',
      'Mental health',
      'MesoBotox',
      'MesoGlow',
      'Mesohair Therapy',
      'Mesotherapies',
      'Mesotherapy',
      'Mesotherapy for Face',
      'Metal Free Crowns & Bridges',
      'Micro Dermabrasion',
      'Micro Discectomy',
      'Micro Ear Surgery',
      'Microalbumin Test',
      'Microdermabrasion',
      'Microscopic Larynx Surgery',
      'Microscopic surgery spine',
      'Microsurgery',
      'Microsurgery of the Larynx',
      'Microvascular & Hand Reconstruction',
      'Mini Abdominoplasty',
      'Mini Port Surgeries',
      'Minimal Invasive Surgery',
      'Minimal invasive surgery',
      'Minimally Invasive',
      'Minimally Invasive Hip Correction',
      'Minimally Invasive Knee Correction',
      'Minimally Invasive Spine Surgery',
      'Minimally Invasive Surgery',
      'Minimally Invasive Urology',
      'Minimally invasive endoscopic surgery.',
      'Modified Osteo-Odonto Keratoprosthesis-MOOKP ( Tooth for a Eye)',
      'Mole & Skin tag removal',
      'Mole Removal',
      'Mother & Child Care',
      'Mouth Body Connection',
      'Multi Speciality Clinic',
      'Multi specialty Hospital ',
      'Multispecialty OPD',
      'Muscle release',
      'Musculoskeletal Infections',
      'Musculoskeletal Pain Management',
      'Muskulo Skeletal',
      'Myelopathy',
      'N.I.C.U.',
      'NEPHROLOGY',
      'NEURO SURGERY',
      'NEUROLOGY',
      'NICU',
      'NICU with 8 Incubators & Ventilators wo IPCU Bed',
      'NO Injection- No Stitch- No Patch Surgery for Cataract',
      'NST,ECG,Pathology',
      'Nail',
      'Nail disorders',
      'Nasal Disorders',
      'Nasal Endoscopy',
      'Nasal Polypectomy',
      'Nasal Septum Surgery',
      'Nebulisations',
      'Neck Pain',
      'Neck Pain Physiotherapy',
      'Neonatal Intensive care unit',
      'Neonatology',
      'Nepherology',
      'Nephrectomy (Kidney Removal)',
      'Nephrology',
      'Nephrology (Kidney)',
      'Nephrology Centre',
      'Nerve compression',
      'Nerve root block',
      'Netralay',
      'Neuro Psychiatry',
      'Neuro Surgery',
      'Neuro-Surgery',
      'Neurology',
      'Neurology & Neurosurgery',
      'Neurology Care',
      'Neurology Department',
      'Neuromuscular Disorders',
      'Neuropathy Assessment',
      'Neuropsychological diagnosis',
      'Neuroradiology',
      'Neurosurgery',
      'Neurourology',
      'Neurovascular',
      'New Born Care',
      'Newborn Jaundice',
      'Nicotine/Tobacco (Smoking) De-addiction Treatment',
      'Nightmares/Bad Dreams',
      'Non Invasive Cardiology',
      'Non Surgical Breast Uplifting Treatment',
      'Non pregnancy (gynaec) problems',
      'Non-Invasive Cardiology',
      'Non-surgical Face Lift',
      'Non-surgical face and body contouring',
      'Normal Delivery',
      'Normal Vaginal Delivery (NVD)',
      'Normal deliveries',
      'Nose Allergy',
      'Nose Surgery-Rhinoplasty',
      'Nose fractures',
      'Nose surgery',
      'Nosebleed (Epistaxis) Treatment',
      'Not from Mumbai?',
      'Nuchal Transluscency Scan',
      'Nuclear Medicine',
      'Nutrition & Dietetics',
      'Nutritional Medicine',
      'OCD',
      'OCUPLASTY CLINIC',
      'OGD Scopy and Cystoscopy',
      'ONCO SURGERY',
      'ONCOLOGY',
      'OPD',
      'OPD Consultation',
      'OPD Scheduler',
      'OPERATION THEATRE COMPLEX',
      'OPERATION THEATRES',
      'OPTHALMOLOGY',
      'ORTHOPAEDICS',
      'OUT PATIENT DEPARTMENT',
      'Obesity',
      'Obesity Management',
      'Obestetrics',
      'Obestriatics & Gynaecology',
      'Obsessive Compulsive Disorder (OCD) Treatment',
      'Obstetric',
      'Obstetrician',
      'Obstetrics',
      'Obstetrics & Gynaecology',
      'Obstetrics & Gynecology',
      'Obstetrics / Antenatal Care',
      'Obstetrics Problems',
      'Obstetrics and Gynaecology',
      'Obstruction while Urinating',
      'Occupational Medicine',
      'Ocular inflammation and uveitis',
      'Oculoplastic Surgery',
      'Oculoplasty',
      'Oculoplasty & Orbital Diseases',
      'Oculoplasty Treatment',
      'On-Call all Pediatric sub-specialization',
      'Onco Surgery',
      'Onco-surgery',
      'Oncology',
      'Oncology (Cancer)',
      'Oncology Care',
      'Oncosurgery',
      'Oncousurgery & Preventive Oncology',
      'Online Counselling',
      'Oophorectomy / Ovariectomy / Ovarian Ablation',
      'Open Prostatectomy',
      'Open/minimally invasive discectomy',
      'Operation Theater',
      'Operation Theatre',
      'Operation Theatre - All Types of Operation',
      'Operation Theatre Suites',
      'Operation Theatres',
      'Ophthalmic Equipments with Microscope ',
      'Ophthalmologic Examination',
      'Ophthalmologic examinations',
      'Ophthalmology',
      'Ophthalmology & Cataract Operations',
      'Opthamology',
      'Optical Coherence Tomography (OCT)',
      'Optical Counter',
      'Oral & Maxillofacial Surgery',
      'Oral Cancer Treatment',
      'Orbital & Optic Nerve Decompression',
      'Orbital Optic Nerve Decompression',
      'Orfit splinting',
      'Organ Transplant Programme',
      'Orthodontics',
      'Orthopaedic / Arthroscopy',
      'Orthopaedic Care',
      'Orthopaedic Centre',
      'Orthopaedic Consultation and Surgery',
      'Orthopaedic Surgery',
      'Orthopaedic doctor',
      'Orthopaedics',
      'Orthopaedics & JT',
      'Orthopaedics & Joint Replacement',
      'Orthopaedics (Bone & Joint)',
      'Orthopedic',
      'Orthopedic Physiotherapy',
      'Orthopedic Surgery',
      'Orthopedic and spine deformity correction surgerywith cell saver',
      'Orthopedics',
      'Orthopedics / Replacement',
      'Orthopedicsurgeries',
      'Osteoporosis Treatment',
      'Other Hair Transplant',
      'Other Services',
      'Other Skin Treatment',
      'Otolaryngology',
      'Our Specialists',
      'Out Patient',
      'Out-Patient Department',
      'Out-Patient Services',
      'Out-patient / office hysteroscopy interventions.',
      'Outreach Clinics',
      'Outstation Clinics',
      'Ovarian Cyst Removal',
      'PAEDIATRIC SURGERY',
      'PAEDIATRICS',
      'PATHOLOGY',
      'PCOD',
      'PCOD& Breast Problems',
      'PCOS/PCOD & women related disorders',
      'PESA',
      'PGD (Pre-implantation genetic  diagnosis)',
      'PGS and Hysteroscopy',
      'PHYSIOTHERAPY',
      'PHYSIOTHERAPY DEPARTMENT',
      'PICU',
      'PLASTIC SURGERY',
      'PRP',
      'PRP Hair Loss Treatment',
      'PRP Hair Transplantation',
      'PRP TREATMENT ',
      'PSYCHIATRY',
      'Pacemaker Implantation',
      'Paediatric Cardiology',
      'Paediatric Ophthalmology',
      'Paediatric Ophthalmology & Squint',
      'Paediatric Orthopaedic',
      'Paediatric and foetal echocardiography',
      'Paediatric surgery',
      'Paediatrics',
      'Paediatrics & Neonatology',
      'Paediatrics - Ortho',
      'Paediatrics / Neonatology',
      'Pain',
      'Pain Management',
      'Pain management',
      'Painless Delivery',
      'Painless Labour',
      'Palliative Care',
      'Pancreas Stone Treatment',
      'PancreasStone Treatment',
      'Pap Smear',
      'Parenting',
      'Parenting Issues & Doubts',
      'Parenting Issues& Doubts',
      'Parking & Security / ATM Facility',
      'Parotid Surgery',
      'Partial Denture (Metal Based)',
      'Pathological Lab',
      'Pathology',
      'Pathology ',
      'Pathology & Microbiology',
      'Pathology (Anatomical, Clinical)',
      'Pathology Lab',
      'Pathology Laboratory',
      'Pediatric',
      'Pediatric Cardiology',
      'Pediatric Clinic',
      'Pediatric Dentistry',
      'Pediatric Dentistry – For The Parents',
      'Pediatric Dentistry – Treatments Offered',
      'Pediatric Department',
      'Pediatric Gastroenterology',
      'Pediatric Neurology',
      'Pediatric Opthalmology',
      'Pediatric Surgery',
      'Pediatric cardiology',
      'Pediatric congenital heart surgeries',
      'Pediatric emergencies',
      'Pediatrics',
      'Pediatrics Ophthalmology',
      'Peel',
      'Peel, Polishing, Lasers',
      'Penis Pain',
      'Peptic / Gastric Ulcer Treatment',
      'Percutaneous Nephrolithotomy',
      'Percutaneous Vertebroplasty for Compression Fracture',
      'Periodontal Flap Surgery',
      'Peripheral angiography with angioplasty',
      'Personality assesment for children &amp; adults',
      'Phacoemulsification Surgery',
      'Pharmacology',
      'Pharmacy',
      'PharmacyCafeteria',
      'Phobias',
      'Phonosurgery',
      'Photofacial',
      'Physical Medicine/Rehab',
      'Physical Therapy / Rehabilitation',
      'Physiotherapy',
      'Physiotherapy ',
      'Physiotherapy Center',
      'Physiotherapy and Rehabilitation',
      'Physiotherapy for Neurological Disorders',
      'Physiotherapy for Sports Injury Rehabilitation',
      'Physiotherepy',
      'Physiotheropy',
      'Pigment Laser',
      'Pigmentation',
      'Pigmentation  Treatments',
      'Piles Surgery',
      'Plantar Fascitis',
      'Plastic Surgery',
      'Platelet-Rich Plasma(PRP)',
      'Platlet Rich Plasma(PRP)',
      'Podiatry',
      'Polyclinic Facilities',
      'Portable X-Ray',
      'Post Traumatic Stress Disorder (PTSD)',
      'Post and Core',
      'Postdelivery care',
      'Pre Marital Problems',
      'Pre and Post Delivery Care',
      'Pre-Clinical & Clinical Research',
      'Precision Attachment Dentures',
      'Preconception counselling',
      'Pregnacy Care',
      'Pregnancy Hypertension (Preeclampsia/ Eclampsia)',
      'Pregnancy Problems',
      'Pregnant Women Counseling',
      'Premarital Counseling',
      'Premarital counselling',
      'Prenatal Listeria',
      'Primary Care',
      'Primary Health Care',
      'Primary Hip and Knee Arthroplasty',
      'Primary and revision - total hip replacement',
      'Prostate Laser Surgery',
      'Prostate Resection Surgery',
      'Prosthetic care and rehabilitation',
      'Prosthetics',
      'Protein loss in urine (proteinuria) management',
      'Prp',
      'Psoriasis Treatment',
      'Psoriatic arthritis',
      'Psychiatric',
      'Psychiatric Department',
      'Psychiatry',
      'PsychiatryRhumatology',
      'Psychometric Testing',
      'Psychosexual Problems',
      'Psychotherapy Adult',
      'Pterygium',
      'Pulmonary Function Test',
      'Pulmonary Medicine',
      'Pulmonology',
      'Pulmonology (Lungs)',
      'Pure Tone Audiometry',
      'RADIOLOGY',
      'RCT - Root Canal Treatment',
      'REFRACTIVE SURGERY CLINIC',
      'RETINA CLINIC',
      'Radiation Oncology',
      'Radiation Therapy',
      'Radical Cystectomy',
      'Radical Prostatectomy',
      'Radiology',
      'Radiology & ECG',
      'Radiology & Imaging',
      'Rapid 360 Acne Clear',
      'Reactive arthritis ',
      'Receeding Gum',
      'Reconstruction & Rehabilitation',
      'Reconstructive Middle Ear Surgery',
      'Reconstructive Urology',
      'Reduced Vision',
      'Refractive Surgery',
      'Removal of Warts,Corns,Skin tags etc',
      'Removal of extruded intervertebral disc',
      'Renovascular Diseases',
      'Retina',
      'Retina Examination',
      'Retina Surgery and Lasik',
      'Retina Treatment:',
      'Retinal Diseases',
      'Retinal Procedures',
      'Revision Hip and Knee Arthroplasty',
      'Revision Surgery',
      'RevisionHip and Knee Arthroplasty',
      'Rheumatic Heart Disease Treatment',
      'Rheumatoid Arthritis Treatment',
      'Rheumatoid arthritis',
      'Rheumatology',
      'Rhinology',
      'Rhinoplasty',
      'Robotic Surgery',
      'Room Options',
      'Rooms',
      'Round the Clock RMO',
      'Routine Consultation',
      'Routine USG',
      'SGOT Test',
      'SKIN CARE',
      'SONOGRAPHY',
      'SPECIAL ROOMS',
      'SPEECH THERAPY',
      'SQUINT AND PAEDRIATIC',
      'STRESS URINARY INCONTINENCE ',
      'SVG graft angiography',
      'Safety and Security',
      'Salicyclic Peel',
      'Salivary Gland Surgery',
      'Scaling / Polishing',
      'Scaling/Polishing',
      'Scalp Ailments',
      'Scalp Treatment',
      'Scar Removal',
      'Scar Revision Surgery',
      'Scar Treatment',
      'Scheurmann disease',
      'Scientific Slimming Programme',
      'Scoliosis',
      'Scoliosis Correction',
      'Selective Multi-fetal reduction',
      'Semen analysis',
      'Septoplasty',
      'Sex & Marriage Counselling',
      'Sexologist',
      'Sexologist ',
      'Sexologist/ Sexual-Relationship Counselling/ PE/ ED',
      'Short Scar Lift',
      'Shoulder Arthroscopy & Reconstruction',
      'Shoulder Pain',
      'Shoulder Replacement',
      'Simple primary arthroplasty',
      'Simultaneous Bilateral Knee Arthroplasty',
      'Single Balloon',
      'Single Port Surgeries',
      'Single Visit Root Canals',
      'Single sitting RCT',
      'Sinus Headache Treatment',
      'Sinusitis',
      'Skeletal Dysplasias',
      'Skin',
      'Skin & Venereal Diseases',
      'Skin Ailments',
      'Skin Biopsy',
      'Skin Boosters and Fillers',
      'Skin Care',
      'Skin Disease Treatment',
      'Skin Lightening',
      'Skin Peeling',
      'Skin Polishing',
      'Skin Polishing  ',
      'Skin Rash Treatment',
      'Skin Services',
      'Skin Tag Surgical Removal',
      'Skin Tightening',
      'Skin Treatment',
      'Skin Treatments',
      'Skin Whitening',
      'Skin allergy treatments',
      'Skin and Cosmetics',
      'Skull Base Surgery',
      'Skull base surgery',
      'Sleep Apnea',
      'Sleep Disorders',
      'Slipped Disk',
      'Slipped disc',
      'Smile Design',
      'Smile Makeovers',
      'Snoring & Sleep',
      'Snoring / Sleep Apnea',
      'Sonography & CD',
      'Speaking Difficulty',
      'Speciality Clinic',
      'Speciality Clinics',
      'Specialties',
      'Specialty Clinics',
      'Speech Audiometry',
      'Speech Pathology & Audiology',
      'Speech Threrapy',
      'Sperm Retrieval',
      'Spinal Cord Injury Treatment',
      'Spinal Deformity Correction',
      'Spinal Disc Surgery',
      'Spinal Diseases',
      'Spinal Disorders',
      'Spinal Fusion',
      'Spinal Rehabilitation',
      'Spinal Surgery',
      'Spinal Therapy',
      'Spinal cord tumors',
      'Spinal deformities correction',
      'Spinal deformity',
      'Spinal stenosis',
      'Spinalcord',
      'Spine Deformity correction surgery',
      'Spine Injury',
      'Spine Rehabilitation',
      'Spine Surgery',
      'Spine clinic',
      'Spine fracture and trauma',
      'Spine instrumentation',
      'Spine specialist',
      'Spine surgeon',
      'Spine tumour',
      'Spirometry',
      'Spondylitis',
      'Spondylolisthesis',
      'Spondylosis',
      'Sports Medicine Clinic',
      'Squint',
      'Stabilisation of spine',
      'Stapedectomy',
      'Stapler surgery for piles',
      'Stem Cell Therapy',
      'Stents Available',
      'Sterile Ear Piercing',
      'Stone Removal',
      'Stress Management',
      'Stress Test',
      'Stress urinary incontinence',
      'Stretch Marks Treatment',
      'Stretch MarksRemoval',
      'Stroke Clinic',
      'Stroke management',
      'Sub Arachnoid',
      'Subcision',
      'Subincision',
      'Suicidal Behavior',
      'Sun Spots, Age Spots, And Other Pigmented Lesions',
      'Superficial femoralartery atherectomy using 2D echocardiography with colour Doppler',
      'Support Groups',
      'Surface Replacement Arthroplasty (ASR)',
      'Surgery',
      'Surgery Clinic',
      'Surgery Of The Facial Nerve',
      'Surgery Theatre',
      'Surgery for Snoring',
      'Surgical Critical Care',
      'Surgical Gastroenterology',
      'Surgical Oncology',
      'Surgical Services',
      'Surgical Unit',
      'Surgical problems correction in babies and children',
      'Surrogacy',
      'Swallowing Problem',
      'Swallowing disorders',
      'Systemic lupus erythematosus management',
      'Systemic sclerosis ',
      'TB & Chest Medicine',
      'TB spine',
      'TESA',
      'TMT',
      'TOF surgery',
      'TPAs',
      'Tattoo Removal',
      'Technical Expertise',
      'Teeth Whitening',
      'Teeth Whitening/Bleaching',
      'Tendon Injuries',
      'Test tube Baby Centre',
      'Testicular Surgery',
      'Therapeutic Endoscopy',
      'Thoracic Surgery',
      'Thoracic spine',
      'Thoracoscopy',
      'Thread Lift',
      'Three Operation Theaters',
      'Throat Cancer Detection',
      'Throat Surgery',
      'Throat and Voice Problems',
      'Thyroid',
      'Thyroid Disorder Treatment',
      'Thyroid Surgery',
      'Thyroplasty',
      'Tinnitus Evaluation / Management',
      'Tinnitus Vertigo',
      'Tonometry',
      'Tonsil surgery',
      'Tonsillectomy',
      'Tonsillitis',
      'Tonsillitis Treatment',
      'Tooth Extraction',
      'Tooth Jewellery',
      'Tooth Veneers / Laminates',
      'Tooth in an Hour',
      'Total Heart Care & diabetic Clinic',
      'Total Joint Reconstruction',
      'Total Knee and hip replacemen',
      'Total Laparoscopic Hysterectomy',
      'Total lap hysterectomies',
      'Trans-oesophageal echocardiography',
      'Transfusion Medicine',
      'Transplant',
      'Transurethral Incision of The Prostate (TUIP)',
      'Transurethral Resection of Bladder Tumor',
      'Transurethral Resection of The Prostate (TURP)',
      'Trauma',
      'Trauma / Emergency Care',
      'Trauma Surgery',
      'Trauma care',
      'Travel Vaccination and Consultation',
      'Tread Mill Test (TMT)',
      'Treadmill Stress Test',
      'Treatment Dengue',
      'Treatment For Gum Disease',
      'Treatment Of Erectile Dysfunction',
      'Treatment for Macular Degeneration',
      'Treatment of fractures and other injuries in children',
      'Trichology',
      'Tubectomy/Tubal Ligation',
      'Tuberculosis (TB) Treatment',
      'Tuberculosis of Spine',
      'Tummy Tuck',
      'Tummy Tuck Surgery / Abdominoplasty',
      'Two-Dimensional Echocardiogram (2D Echo)',
      'Tympanoplasty',
      'ULTRASONOGRAPHY / COLOUR DOPPLER',
      'UPS for all Departments',
      'UROLOGY',
      'UTI',
      'Ultra Sonography',
      'Ultra Sonography (24 hours) logic P6',
      'Ultra Sonography (Routine & Dopplers)',
      'Ultrasonic Liposuction',
      'Ultrasonography',
      'Ultrasonography - Pelvic',
      'Ultrasound',
      'Ultrasound / Fibroscan',
      'Ultrasound Imaging',
      'Uncontrolled Diabetes ',
      'Undernourished and Lifeless Hair',
      'Unicompartmental Knee Replacement',
      'Unilateral Salpingo-Oophorectomy',
      'Unwanted Body Hair',
      'Ureaplasma urealyticum infection',
      'Ureteroscopy (URS)',
      'Ureterostomy',
      'Urethrotomy',
      'Urinary Incontinence (Ui) Treatment',
      'Urinary Tract / Bladder Stones Treatment',
      'Urinary Tract Infection (UTI)',
      'Urinary Tract Obstruction',
      'Urine Cytology',
      'Uro-gynacology',
      'Urogynaecology',
      'Urology',
      'Urology Consultation',
      'Urology/ Oncology/ Neurology Clinic',
      'Urostomy',
      'Urosurgery',
      'Uterus RemovalSurgery',
      'VAGINAL REJUVENATION',
      'VIOLENT PATIENTMANAGEMENT',
      'VOICE disorders correction',
      'Vaccination',
      'Vaccination(cervical cancer)',
      'Vaccination/ Immunization',
      'Vaccinations',
      'Vagina Surgery',
      'Vaginal Infection Treatment',
      'Vaginoplasty',
      'Valve Replacements',
      'Vampire Facelift',
      'Varicocele Surgery',
      'Vascular & Endovascular Surgery',
      'Vascular Surgery',
      'Vasculitis ',
      'Vein Therapy',
      'Veneers / Laminates',
      'Ventilator & ICU Facility',
      'Ventilator & Pacemaker',
      'Vesicoureteral reflux',
      'Veterinary Services',
      'Video Endoscopy - Gastroscopy, Colonoscopy, Bronchoscopy',
      'Video Recording Of Ear, Nose And Throat From Oral Camera',
      'Video-assisted thoracoscopy',
      'Viral Fever',
      'Viral Fever Treatment',
      'Visitors Cafe',
      'Visual Field Test',
      'Vitreo Retina',
      'Vitreo Retinal',
      'Vocal Cord paralysis',
      'Voice Problem',
      'Vulvar Cancer Surgery',
      'WARDS',
      'Waiting Lounge',
      'Wart Removal',
      'Waxing',
      'Weight Loss Diet Counseling',
      'Weight Loss Treatment',
      'Weight Loss/Bariatric Surgery',
      'Well Woman Healthcheck',
      'Well- equipped operation theateres',
      'Wellness',
      'Wellness Clinic',
      'Wisdom Molar Extractions',
      "Women's Care",
      'Women’s Health care – Depatment of Obstetrics & Gynaecology',
      'Wound Care',
      'Wrinkle Treatment',
      'Wrist & elbow arthroscopy',
      'X-Ray',
      'Your Comfort Matters',
      'Youth Services',
      'allergic detection',
      'bladder stones',
      'blood bank',
      'bridal packages',
      'cardiac care',
      'chemical peel',
      'consultation',
      'cornea transplant',
      'cosmetic',
      'dentist',
      'diabetic eye care',
      'dialsis',
      'discectomy',
      'ear surgery with microscope',
      'ectopic pregnancies',
      'endoscopic surgeries',
      'family planning and full contraceptive services',
      'family planning centre',
      'fertility enhancing diagnostic & operative laparoscopy and hysteroscopy as well as out-patient / office hysteroscopic interventions',
      'fracture',
      'fractures',
      'general surgery',
      'geriatric orthopaedics',
      'glaucoma evaluation',
      'homeopathy ',
      'imag',
      'info na',
      'joint replacements - shoulder, elbow, small joints of hands and feet',
      'keratoplasty',
      'laminectomy',
      'laparascopic surgery',
      'laparoscopic expertise includes management of complex ovarian cysts',
      'laser hair removal',
      'lasik',
      'menopause advice',
      'mommy makeover',
      'nasal septum surgery',
      'non-surgical management of back pain',
      'ocular trauma care',
      'oculoplasty',
      'operative laparoscopy and hysteroscopy',
      'orthopodology',
      'osteoarthritis',
      'pediatric ortho',
      'perimetry',
      'phacoemulsification cataract surgery',
      'physician',
      'plastic surgery',
      'plastic surgery of nose',
      'prp',
      'psychology ',
      'refractive eye surgery',
      'sSurgical Oncology',
      'snoring',
      'spinal instrumentation',
      'spine',
      'spine surgeon',
      'spine surgery',
      'sports injuries',
      'sports medicine',
      'test arti',
      'tonsillectomy',
      'total lap hysterectomies',
      'vertebroplasty',
      'vertigo',
      'work related counselling'
    ];
  }
}
